version: '3.3'

volumes:
  pg_data:
  backend_static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: zxcded/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/django_static/
      - media:/media/
  frontend:
    container_name: foodgram-front
    image: zxcded/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    build:
      context: ./nginx
    ports:
      - 8000:80
    volumes:
      - backend_static:/django_static/
      - media:/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/